name: Ping Streamlit App

on:
  schedule:
    - cron: "*/30 * * * *"  # A cada 30 minutos
  workflow_dispatch:        # Permite rodar manualmente também

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: |
          curl -s -A "Mozilla/5.0" https://agente-ia-nova-aurora.streamlit.app || echo "Falha ao pingar"
