name: Ping Streamlit (via browser)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (dummy)
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar Playwright
        run: |
          npm install playwright
          npx playwright install  # ← esta linha é essencial!

      - name: Visitar o app como navegador
        run: |
          node -e "
          const { chromium } = require('playwright');
          (async () => {
            const browser = await chromium.launch();
            const page = await browser.newPage();
            await page.goto('https://agente-ia-nova-aurora.streamlit.app', { waitUntil: 'load' });
            await new Promise(r => setTimeout(r, 8000));
            await browser.close();
          })();"
