name: Ping Streamlit (via browser)

on:
  schedule:
    - cron: "*/30 * * * *"  # Executa a cada 30 minutos
  workflow_dispatch:        # Também pode ser executado manualmente

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (dummy)
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar Playwright e navegador
        run: |
          npm install playwright
          npx playwright install

      - name: Visitar o app como navegador
        run: |
          node -e "
          const { chromium } = require('playwright');
          (async () => {
            const browser = await chromium.launch({ headless: true });
            const page = await browser.newPage();
            await page.goto('https://agente-ia-nova-aurora.streamlit.app', { waitUntil: 'networkidle' });
            await page.waitForTimeout(5000); // espera a renderização

            // Interação leve: scroll na página
            await page.evaluate(() => window.scrollBy(0, 300));
            await page.waitForTimeout(3000);

            await browser.close();
          })();"
